id: AE833AA18
title: 'The Annihilator of Damsi Demons: A Prayer to the Lineage of the Great and
  Glorious Dorje Drolö'
type: translation
pechas:
- I65823683
- I3CB11EC8
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:14:55.742815
  last_modified_at: 2023-01-04 12:14:55.742820
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I65823683/BA40: BF8D
  I3CB11EC8/F305: BF8D
